name: Decibel Cubed Productions
favicon: null
layout_spectrum: 0.50488
typography_spectrum: 0.78527
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.026994258165359497
  lightness: 0.853799034608528
  saturation: 0.8462366082239896
  rhythmicContrast: 0.6161755898501724
purpose: []
